# Generated by Django 4.2.7 on 2025-08-20 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(max_length=200)),
                ('full_description', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='rooms/hero/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='rooms/thumbs/')),
                ('base_price', models.DecimalField(decimal_places=2, default=30.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('reserved', 'Reservada')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='rooms.room')),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('room', 'date', 'time')},
            },
        ),
    ]
