# Generated by Django 4.2.7 on 2025-08-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='rooms_room_is_acti_2e361c_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['slug'], name='rooms_room_slug_3e98b7_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['room', 'date'], name='rooms_times_room_id_6d9472_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['status'], name='rooms_times_status_6ef3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date', 'time'], name='rooms_times_date_fda53e_idx'),
        ),
    ]
