# Generated by Django 4.2.7 on 2025-08-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_change_image_fields_to_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
