# Generated by Django 4.2.7 on 2025-10-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_video_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('status', 'reserved'), _connector='OR'), fields=('room', 'date', 'time', 'status'), name='unique_active_timeslot'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('room', 'date', 'time'), name='unique_room_datetime'),
        ),
    ]
